### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by douglasdcm** [jakob-bagterp/browserist#308]
This library is very interesting specially for make the code simpler. I was reading the code and it seems to be very complete too. I just didn't see code related to "Alerts". I'm not sure also if you have an interest in add asynchronous functions to this library. I'm working on library to it. Let me know.

I'll use this library in my personal projects to find issue that can help this project to grow!

Congratulation for the job!

**Comment by jakob-bagterp** [comment]
@douglasdcm: Thanks! That's highly appreciated.

One milestone on my roadmap is adding documentation so it's easier to get started.

Regarding async functionality, that could be interesting. I have optimised the internals a little where it made sense. But what use cases can you come up with?

**Comment by douglasdcm** [comment]
@jakob-bagterp 
> One milestone on my roadmap is adding documentation so it's easier to get started.

Great, this is something I can help as soon as I start using this library.

> What use cases for async can you think of?

I have a crawler that get links from websites, navigate to them and get the complete body of each page. The first version was made synchronously and for 150 websites it spent 4 hours to collect all data. Now, I'm migrating to an asynchronous version using a simple library I created, but it is under test. My lib is a little verbose, like Selenium is, so I need to get elements first to perform actions. Your lib does the same thing, but with less lines of code. I can try to build some similar functions like yours, for example, `browser.input.value("//xpath/to/input", "Lorem ipsum")` but to perform asynchronous calls. It'd be a plus in this library. Nothing existent need to be changed

**Comment by jakob-bagterp** [comment]
Good thoughts, @douglasdcm. Thanks!

Let's imagine a simple web-scraping flow:

1. Instantiate an automated browser
2. Request a URL, e.g. example.com/some/page
3. Get text from elements and save the data
4. Close the browser

As this is a sequence that can only be performed step by step – i.e. you can't do step 3 before step 1 and 2 respectively have been completed – it's rather difficult to perform this flow asynchronously. The nature of the task is the limitation, not the code.

However, if you have flows that covers 150 websites, I'm sure you can boost performance by running multiple tasks in parallel. Browserist is actually designed with this in mind from a stability and performance perspective, but also to easily scale, for instance, quality assurance tasks across...

* different browser types with the `BrowserSettings` and `BrowserType` configurations
* different user roles with login credentials and the `LoginForm1Step` and `LoginForm2Steps` for the login combo
* different viewports with the `DeviceViewportSize` and collection of common mobile devices for Apple, Google, Samsung, etc.
* etc.

... simply as many configurations are standardised (unlike Seleniums many configuration quirks).

An example:

```python
import asyncio
from browserist import Browser, BrowserSettings, BrowserType

async def open_website_with(settings: BrowserSettings):
    with Browser(settings) as browser:
        print(f"1. Opening {settings.type.name} browser")
        browser.open.url("http://example.com/")
        print(f"2. Page loaded with {settings.type.name} browser")
        await asyncio.sleep(.1)
        print(f"3. Closing {settings.type.name} browser")

async def main():
    chrome = BrowserSettings(type=BrowserType.CHROME)
    edge = BrowserSettings(type=BrowserType.EDGE)
    firefox = BrowserSettings(type = BrowserType.FIREFOX)

    async with asyncio.TaskGroup() as task_group:
        task_group.create_task(open_website_with(chrome))
        task_group.create_task(open_website_with(edge))
        task_group.create_task(open_website_with(firefox))

asyncio.run(main())
```

This will print in the terminal:

```terminal
1. Opening CHROME browser
2. Page loaded with CHROME browser
1. Opening EDGE browser
2. Page loaded with EDGE browser
1. Opening FIREFOX browser
2. Page loaded with FIREFOX browser
3. Closing CHROME browser
3. Closing EDGE browser
3. Closing FIREFOX browser
```

I plan to add more documentation for this project soon, including examples of how to increase performance and scale automated browsers with asynchronous tasks. Refer to issue #320, and allow me to close your request. I hope this finds you well, and I wish you a lovely day.

PS: Apologies for the late reply. This is just a hobby project, and my job got me hanging.

**Comment by jakob-bagterp** [comment]
It's also possible to use multi-threading, which runs tasks concurrently and often much faster than async:

```python
from threading import Thread
from browserist import Browser, BrowserSettings, BrowserType

class BrowserThread(Thread):
    def __init__(self, settings: BrowserSettings):
        Thread.__init__(self)
        self.settings: BrowserSettings = settings
  
    def run(self):
        with Browser(self.settings) as browser:
            print(f"1. Opening {self.settings.type.name} browser")
            browser.open.url("http://example.com/")
            print(f"2. Page loaded with {self.settings.type.name} browser")
            print(f"3. Closing {self.settings.type.name} browser")

def main():
    chrome = BrowserSettings(type=BrowserType.CHROME)
    edge = BrowserSettings(type=BrowserType.EDGE)
    firefox = BrowserSettings(type=BrowserType.FIREFOX)

    threads: list[Thread] = []
    for browser_setting in [chrome, edge, firefox]:
        thread = BrowserThread(browser_setting)
        thread.start()
        threads.append(thread)

    for thread in threads:
        thread.join()

if __name__ == "__main__":
    main()
```

PS: As you may know, be aware of the extra resources (CPU load and memory) needed to spin up multiple browsers.

**Comment by douglasdcm** [comment]
Hey @jakob-bagterp  thanks a lot for the very well explained scenario. It is something I'm going to try out!

**Comment by jakob-bagterp** [comment]
De nada, @douglasdcm. You're welcome.

Quick update after playing around with the three different approaches to run the simplistic flows in concurrently and measuring their performance compared to a linear flow. Results:

```terminal
### NOT HEADLESS ###
### AVERAGE RESULTS ###
Number of rounds: 5
Linear: 8.59 seconds (min 8.55, max 8.62)
Asynchronous: 8.42 seconds (min 8.33, max 8.48)
Multi-threading: 4.24 seconds (min 4.20, max 4.29)
Multi-processing: 4.20 seconds (min 3.69, max 6.05)
```

Multi-processing is slightly faster than multi-threading, though both are almost twice as fast as the linear or asynchronous.

And you can gain a little more by running the browsers in headless mode and with images disabled, e.g. `BrowserSettings(type=BrowserType.CHROME, headless=True, disable_images=True)`, and with the added benefit that you can let it run as a background task while doing something else. Results:

```terminal
### HEADLESS ###
### AVERAGE RESULTS ###
Number of rounds: 5
Linear: 10.46 seconds (min 6.34, max 15.78)
Asynchronous: 8.01 seconds (min 6.15, max 12.11)
Multi-threading: 4.03 seconds (min 3.98, max 4.07)
Multi-processing: 3.60 seconds (min 3.57, max 3.65)
```

I hope this is helpful and inspires you to try out different approaches to optimising your web-scraping.

**Comment by jakob-bagterp** [comment]
@douglasdcm: Quick update. I've started compiling documentation for the project. Find more details here:

https://jakob-bagterp.github.io/browserist/

It's work in progress so there will be more updates the coming days. But please let me know if you find anything missing?

Enjoy your summer and have a lovely weekend!
