### ISSUE TITLE
How do I run the tests?

### ISSUE THREAD

**Issue by douglasdcm** [jakob-bagterp/browserist#369]
Hi, I'd like to know the Python version you are using. I want to run the tests locally. There are any instructions to run them ourI can 
 just use pytest?

**Comment by jakob-bagterp** [comment]
@douglasdcm: Okay. You can use Python 3.10 or 3.11. And yes, simply execute `pytest` to run the tests. Find instructions [here](https://github.com/jakob-bagterp/browserist/tree/master/test), and you may need to install dependencies including a [browser driver](https://jakob-bagterp.github.io/browserist/getting-started/browser-drivers/) (default Chrome or Edge if you're using Windows).

Let me know if you have any issues.
